version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel
    ports:
      - "8000:8000"
    working_dir: /var/www
    entrypoint: [ "sh", "-c", "composer install && php artisan migrate &&  php artisan serve --host=0.0.0.0 --port=8000" ]

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel_task
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
